{
 "title": "Kubernetes节点监控",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(node_cpu, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU  使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(1 - avg(rate(node_cpu{instance=~\"$Node.*\",mode=\"idle\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "MEM  使用率（GB）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{instance=~\"$Node.*\"} - node_memory_MemAvailable{instance=~\"$Node.*\"}) / 1024 / 1024 / 1024 / round(sum(machine_memory_bytes{instance=~'$Node.*'}) / 1024 / 1024 / 1024) * 100"
    }
   ]
  },
  {
   "title": "最大磁盘空间使用率（GB）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(node_filesystem_size{instance=~\"$Node.*\"} - node_filesystem_free{instance=~\"$Node.*\"} )/max(node_filesystem_size{instance=~\"$Node.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Node 在线率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) / sum(kube_node_status_condition{condition=\"Ready\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU 总核数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node.*\"}))"
    }
   ]
  },
  {
   "title": "CPU  分配数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(container_spec_cpu_quota{instance=~'$Node.*',pod_name!='',container_name!='POD', container_name!=''})/ 100 / 1000)"
    }
   ]
  },
  {
   "title": "CPU 使用数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(1 - rate(node_cpu{instance=~\"$Node.*\",mode=\"idle\"}[2m])))"
    }
   ]
  },
  {
   "title": "MEM  总量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(machine_memory_bytes{instance=~'$Node.*'}) / 1024 / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "MEM  分配量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(container_spec_memory_limit_bytes{instance=~'$Node.*',pod_name!='',container_name!='POD', container_name!=''}) / 1000 / 1000 / 1000)"
    }
   ]
  },
  {
   "title": "MEM  使用量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(node_memory_MemTotal{instance=~\"$Node.*\"} - node_memory_MemAvailable{instance=~\"$Node.*\"}) / 1024 / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "最大磁盘空间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(max(node_filesystem_size{instance=~\"$Node.*\"}) / 1024 / 1024 /1024)"
    }
   ]
  },
  {
   "title": "最大磁盘空间使用量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(max(node_filesystem_size{instance=~\"$Node.*\"} - node_filesystem_free{instance=~\"$Node.*\"}) / 1024 /1024/1024)"
    }
   ]
  },
  {
   "title": "正常 Node 数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}))"
    }
   ]
  },
  {
   "title": "异常  Node 数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"}))",
     "legendFormat": "异常 Node 数"
    }
   ]
  },
  {
   "title": "Node 数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(count(kube_node_status_condition{condition=\"Ready\",status=\"true\"}))",
     "legendFormat": "Node 数量"
    }
   ]
  },
  {
   "title": "集群 Service 总数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(kube_service_info)", "legendFormat": "Service 数量" }
   ]
  },
  {
   "title": "集群 Pod 总数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(kube_pod_status_ready{condition='true'}))",
     "legendFormat": "Running"
    },
    {
     "expr": "round(sum(kube_pod_status_scheduled{condition='false'}))",
     "legendFormat": "Pending"
    },
    {
     "expr": "round(sum(kube_pod_status_ready{condition='false'}))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Load 负载",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$Node.*\"})",
     "legendFormat": "load 1"
    },
    {
     "expr": "avg(node_load5{instance=~\"$Node.*\"})",
     "legendFormat": "load 5"
    },
    {
     "expr": "avg(node_load15{instance=~\"$Node.*\"})",
     "legendFormat": "load 15"
    }
   ]
  },
  {
   "title": "CPU 利用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(1 - avg(rate(node_cpu{instance=~\"$Node.*\",mode=\"idle\"}[5m]))) * 100",
     "legendFormat": "CPU 使用率"
    }
   ]
  },
  {
   "title": "MEM 使用量 (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{instance=~\"$Node.*\"}) / 1024 / 1024 / 1024",
     "legendFormat": "MEM 总量 (GB)"
    },
    {
     "expr": "sum(node_memory_MemTotal{instance=~\"$Node.*\"} - node_memory_MemAvailable{instance=~\"$Node.*\"}) / 1024 / 1024 / 1024",
     "legendFormat": "MEM 使用量 (GB)"
    }
   ]
  },
  {
   "title": "磁盘吞吐（MB/s）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_bytes_read{instance=~\"$Node.*\"}[5m])) / 1024 / 1024",
     "legendFormat": "磁盘读吞吐"
    },
    {
     "expr": "avg(rate(node_disk_bytes_written{instance=~\"$Node.*\"}[5m])) / 1024 / 1024",
     "legendFormat": "磁盘写吞吐"
    }
   ]
  },
  {
   "title": "磁盘 IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_reads_completed{instance=~\"$Node.*\"}[5m]))",
     "legendFormat": "磁盘读 IOPS"
    },
    {
     "expr": "avg(rate(node_disk_writes_completed{instance=~\"$Node.*\"}[5m]))",
     "legendFormat": "磁盘写 IOPS"
    }
   ]
  },
  {
   "title": "网卡吞吐（MB/s）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_network_receive_bytes{instance=~\"$Node.*\",device=\"ens3\"}[5m])) / 1024 / 1024 or avg(rate(node_network_receive_bytes{instance=~\"$Node.*\",device=\"eth0\"}[5m])) / 1024 / 1024",
     "legendFormat": "网卡接收速率"
    },
    {
     "expr": "avg(rate(node_network_transmit_bytes{instance=~\"$Node.*\",device=\"ens3\"}[5m])) / 1024 / 1024 or avg(rate(node_network_transmit_bytes{instance=~\"$Node.*\",device=\"eth0\"}[5m])) / 1024 / 1024",
     "legendFormat": "网卡发送速率"
    }
   ]
  },
  {
   "title": "网卡数据包",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_network_receive_packets{instance=~\"$Node.*\",device=\"ens3\"}[5m])) or avg(rate(node_network_receive_packets{instance=~\"$Node.*\",device=\"eth0\"}[5m])) ",
     "legendFormat": "网卡接收数据包"
    },
    {
     "expr": "avg(rate(node_network_transmit_packets{instance=~\"$Node.*\",device=\"ens3\"}[5m])) or avg(rate(node_network_transmit_packets{instance=~\"$Node.*\",device=\"eth0\"}[5m])) ",
     "legendFormat": "网卡发送数据包"
    }
   ]
  },
  {
   "title": "网卡丢包数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_network_receive_drop{instance=~\"$Node.*\",device=\"ens3\"}[5m])) or avg(rate(node_network_receive_drop{instance=~\"$Node.*\",device=\"eth0\"}[5m]))",
     "legendFormat": "网卡 接收丢包数"
    },
    {
     "expr": "avg(rate(node_network_transmit_drop{instance=~\"$Node.*\",device=\"ens3\"}[5m])) or avg(rate(node_network_transmit_drop{instance=~\"$Node.*\",device=\"eth0\"}[5m]))",
     "legendFormat": "网卡发送丢包数"
    }
   ]
  },
  {
   "title": "最大磁盘空间使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(node_filesystem_size{instance=~\"$Node.*\"} - node_filesystem_free{instance=~\"$Node.*\"} )/max(node_filesystem_size{instance=~\"$Node.*\"}) * 100",
     "legendFormat": "磁盘使用率"
    }
   ]
  }
 ]
}